clc
clear 
close all
fprintf('This program started at %s\n', datestr(now,'HH:MM:SS'))
SNR_dB = -5:5:35;
N = 3;
QPSK_map = sqrt(0.5)*[1+j,-1+j,1-j,-1-j];
dataMSB_LUT = [0 0 1 1];
dataLSB_LUT = [0 1 0 1];
qpsk_symbol_LUT = [1 2 3 4];
a_su = 1;
Ps_dBm = 30;
Ps = 10^((Ps_dBm - 30)/10);
SNR = 10.^(SNR_dB./10);
a = [0.1 0.2 0.7];
PL = 10.^([0 6 12]./10);
Va1 = [0.15/2 a(1) 0.050 1/3];    %NU power coefficients vector
Va2 = [0.15/2 a(2) 0.475 1/3];    %MU power coefficients vector
Va3 = [0.8500 a(3) 0.475 1/3];    %FU power coefficients vector
SVa1 = sqrt(Va1);
SVa2 = sqrt(Va2);
SVa3 = sqrt(Va3);
Iter = 300000;
Data_length = 256;
Frame_length = Data_length/2;
%Lookup table for PANOMA
MLD_LUT_PANOMA = [real(QPSK_map(1))*SVa1(4) + 1j*imag(QPSK_map(1))*SVa1(4) + ...
                  real(QPSK_map(1))*SVa2(4) + 1j*imag(QPSK_map(1))*SVa2(4) + ...
                  real(QPSK_map(1))*SVa3(4) + 1j*imag(QPSK_map(1))*SVa3(4) ...
                  real(QPSK_map(2))*SVa1(3) + 1j*imag(QPSK_map(2))*SVa1(4) + ...
                  real(QPSK_map(1))*SVa2(3) + 1j*imag(QPSK_map(1))*SVa2(4) + ...
                  real(QPSK_map(1))*SVa3(3) + 1j*imag(QPSK_map(1))*SVa3(4) ...
                  real(QPSK_map(3))*SVa1(4) + 1j*imag(QPSK_map(3))*SVa1(3) + ...
                  real(QPSK_map(1))*SVa2(4) + 1j*imag(QPSK_map(1))*SVa2(3) + ...
                  real(QPSK_map(1))*SVa3(4) + 1j*imag(QPSK_map(1))*SVa3(3) ...
                  real(QPSK_map(4))*SVa1(3) + 1j*imag(QPSK_map(4))*SVa1(3) + ...
                  real(QPSK_map(1))*SVa2(3) + 1j*imag(QPSK_map(1))*SVa2(3) + ...
                  real(QPSK_map(1))*SVa3(3) + 1j*imag(QPSK_map(1))*SVa3(3) ...
                  real(QPSK_map(1))*SVa1(2) + 1j*imag(QPSK_map(1))*SVa1(4) + ...
                  real(QPSK_map(2))*SVa2(2) + 1j*imag(QPSK_map(2))*SVa2(4) + ...
                  real(QPSK_map(1))*SVa3(2) + 1j*imag(QPSK_map(1))*SVa3(4) ...
                  real(QPSK_map(2))*SVa1(1) + 1j*imag(QPSK_map(2))*SVa1(4) + ...
                  real(QPSK_map(2))*SVa2(1) + 1j*imag(QPSK_map(2))*SVa2(4) + ...
                  real(QPSK_map(1))*SVa3(1) + 1j*imag(QPSK_map(1))*SVa3(4) ...
                  real(QPSK_map(3))*SVa1(2) + 1j*imag(QPSK_map(3))*SVa1(3) + ...
                  real(QPSK_map(2))*SVa2(2) + 1j*imag(QPSK_map(2))*SVa2(3) + ...
                  real(QPSK_map(1))*SVa3(2) + 1j*imag(QPSK_map(1))*SVa3(3) ...
                  real(QPSK_map(4))*SVa1(1) + 1j*imag(QPSK_map(4))*SVa1(3) + ...
                  real(QPSK_map(2))*SVa2(1) + 1j*imag(QPSK_map(2))*SVa2(3) + ...
                  real(QPSK_map(1))*SVa3(1) + 1j*imag(QPSK_map(1))*SVa3(3) ...
                  real(QPSK_map(1))*SVa1(4) + 1j*imag(QPSK_map(1))*SVa1(2) + ...
                  real(QPSK_map(3))*SVa2(4) + 1j*imag(QPSK_map(3))*SVa2(2) + ...
                  real(QPSK_map(1))*SVa3(4) + 1j*imag(QPSK_map(1))*SVa3(2) ...
                  real(QPSK_map(2))*SVa1(3) + 1j*imag(QPSK_map(2))*SVa1(2) + ...
                  real(QPSK_map(3))*SVa2(3) + 1j*imag(QPSK_map(3))*SVa2(2) + ...
                  real(QPSK_map(1))*SVa3(3) + 1j*imag(QPSK_map(1))*SVa3(2) ...
                  real(QPSK_map(3))*SVa1(4) + 1j*imag(QPSK_map(3))*SVa1(1) + ...
                  real(QPSK_map(3))*SVa2(4) + 1j*imag(QPSK_map(3))*SVa2(1) + ...
                  real(QPSK_map(1))*SVa3(4) + 1j*imag(QPSK_map(1))*SVa3(1) ...
                  real(QPSK_map(4))*SVa1(3) + 1j*imag(QPSK_map(4))*SVa1(1) + ...
                  real(QPSK_map(3))*SVa2(3) + 1j*imag(QPSK_map(3))*SVa2(1) + ...
                  real(QPSK_map(1))*SVa3(3) + 1j*imag(QPSK_map(1))*SVa3(1) ...
                  real(QPSK_map(1))*SVa1(2) + 1j*imag(QPSK_map(1))*SVa1(2) + ...
                  real(QPSK_map(4))*SVa2(2) + 1j*imag(QPSK_map(4))*SVa2(2) + ...
                  real(QPSK_map(1))*SVa3(2) + 1j*imag(QPSK_map(1))*SVa3(2) ...
                  real(QPSK_map(2))*SVa1(1) + 1j*imag(QPSK_map(2))*SVa1(2) + ...
                  real(QPSK_map(4))*SVa2(1) + 1j*imag(QPSK_map(4))*SVa2(2) + ...
                  real(QPSK_map(1))*SVa3(1) + 1j*imag(QPSK_map(1))*SVa3(2) ...
                  real(QPSK_map(3))*SVa1(2) + 1j*imag(QPSK_map(3))*SVa1(1) + ...
                  real(QPSK_map(4))*SVa2(2) + 1j*imag(QPSK_map(4))*SVa2(1) + ...
                  real(QPSK_map(1))*SVa3(2) + 1j*imag(QPSK_map(1))*SVa3(1) ...
                  real(QPSK_map(4))*SVa1(1) + 1j*imag(QPSK_map(4))*SVa1(1) + ...
                  real(QPSK_map(4))*SVa2(1) + 1j*imag(QPSK_map(4))*SVa2(1) + ...
                  real(QPSK_map(1))*SVa3(1) + 1j*imag(QPSK_map(1))*SVa3(1) ...%%%
                  real(QPSK_map(1))*SVa1(1) + 1j*imag(QPSK_map(1))*SVa1(4) + ...
                  real(QPSK_map(1))*SVa2(1) + 1j*imag(QPSK_map(1))*SVa2(4) + ...
                  real(QPSK_map(2))*SVa3(1) + 1j*imag(QPSK_map(2))*SVa3(4) ...
                  real(QPSK_map(2))*SVa1(2) + 1j*imag(QPSK_map(2))*SVa1(4) + ...
                  real(QPSK_map(1))*SVa2(2) + 1j*imag(QPSK_map(1))*SVa2(4) + ...
                  real(QPSK_map(2))*SVa3(2) + 1j*imag(QPSK_map(2))*SVa3(4) ...
                  real(QPSK_map(3))*SVa1(1) + 1j*imag(QPSK_map(3))*SVa1(3) + ...
                  real(QPSK_map(1))*SVa2(1) + 1j*imag(QPSK_map(1))*SVa2(3) + ...
                  real(QPSK_map(2))*SVa3(1) + 1j*imag(QPSK_map(2))*SVa3(3) ...
                  real(QPSK_map(4))*SVa1(2) + 1j*imag(QPSK_map(4))*SVa1(3) + ...
                  real(QPSK_map(1))*SVa2(2) + 1j*imag(QPSK_map(1))*SVa2(3) + ...
                  real(QPSK_map(2))*SVa3(2) + 1j*imag(QPSK_map(2))*SVa3(3) ...
                  real(QPSK_map(1))*SVa1(3) + 1j*imag(QPSK_map(1))*SVa1(4) + ...
                  real(QPSK_map(2))*SVa2(3) + 1j*imag(QPSK_map(2))*SVa2(4) + ...
                  real(QPSK_map(2))*SVa3(3) + 1j*imag(QPSK_map(2))*SVa3(4) ...
                  real(QPSK_map(2))*SVa1(4) + 1j*imag(QPSK_map(2))*SVa1(4) + ...
                  real(QPSK_map(2))*SVa2(4) + 1j*imag(QPSK_map(2))*SVa2(4) + ...
                  real(QPSK_map(2))*SVa3(4) + 1j*imag(QPSK_map(2))*SVa3(4) ...
                  real(QPSK_map(3))*SVa1(3) + 1j*imag(QPSK_map(3))*SVa1(3) + ...
                  real(QPSK_map(2))*SVa2(3) + 1j*imag(QPSK_map(2))*SVa2(3) + ...
                  real(QPSK_map(2))*SVa3(3) + 1j*imag(QPSK_map(2))*SVa3(3) ...
                  real(QPSK_map(4))*SVa1(4) + 1j*imag(QPSK_map(4))*SVa1(3) + ...
                  real(QPSK_map(2))*SVa2(4) + 1j*imag(QPSK_map(2))*SVa2(3) + ...
                  real(QPSK_map(2))*SVa3(4) + 1j*imag(QPSK_map(2))*SVa3(3) ...
                  real(QPSK_map(1))*SVa1(1) + 1j*imag(QPSK_map(1))*SVa1(2) + ...
                  real(QPSK_map(3))*SVa2(1) + 1j*imag(QPSK_map(3))*SVa2(2) + ...
                  real(QPSK_map(2))*SVa3(1) + 1j*imag(QPSK_map(2))*SVa3(2) ...
                  real(QPSK_map(2))*SVa1(2) + 1j*imag(QPSK_map(2))*SVa1(2) + ...
                  real(QPSK_map(3))*SVa2(2) + 1j*imag(QPSK_map(3))*SVa2(2) + ...
                  real(QPSK_map(2))*SVa3(2) + 1j*imag(QPSK_map(2))*SVa3(2) ...
                  real(QPSK_map(3))*SVa1(1) + 1j*imag(QPSK_map(3))*SVa1(1) + ...
                  real(QPSK_map(3))*SVa2(1) + 1j*imag(QPSK_map(3))*SVa2(1) + ...
                  real(QPSK_map(2))*SVa3(1) + 1j*imag(QPSK_map(2))*SVa3(1) ...
                  real(QPSK_map(4))*SVa1(2) + 1j*imag(QPSK_map(4))*SVa1(1) + ...
                  real(QPSK_map(3))*SVa2(2) + 1j*imag(QPSK_map(3))*SVa2(1) + ...
                  real(QPSK_map(2))*SVa3(2) + 1j*imag(QPSK_map(2))*SVa3(1) ...
                  real(QPSK_map(1))*SVa1(3) + 1j*imag(QPSK_map(1))*SVa1(2) + ...
                  real(QPSK_map(4))*SVa2(3) + 1j*imag(QPSK_map(4))*SVa2(2) + ...
                  real(QPSK_map(2))*SVa3(3) + 1j*imag(QPSK_map(2))*SVa3(2) ...
                  real(QPSK_map(2))*SVa1(4) + 1j*imag(QPSK_map(2))*SVa1(2) + ...
                  real(QPSK_map(4))*SVa2(4) + 1j*imag(QPSK_map(4))*SVa2(2) + ...
                  real(QPSK_map(2))*SVa3(4) + 1j*imag(QPSK_map(2))*SVa3(2) ...
                  real(QPSK_map(3))*SVa1(3) + 1j*imag(QPSK_map(3))*SVa1(1) + ...
                  real(QPSK_map(4))*SVa2(3) + 1j*imag(QPSK_map(4))*SVa2(1) + ...
                  real(QPSK_map(2))*SVa3(3) + 1j*imag(QPSK_map(2))*SVa3(1) ...
                  real(QPSK_map(4))*SVa1(4) + 1j*imag(QPSK_map(4))*SVa1(1) + ...
                  real(QPSK_map(4))*SVa2(4) + 1j*imag(QPSK_map(4))*SVa2(1) + ...
                  real(QPSK_map(2))*SVa3(4) + 1j*imag(QPSK_map(2))*SVa3(1) ...%%%   
                  real(QPSK_map(1))*SVa1(4) + 1j*imag(QPSK_map(1))*SVa1(1) + ...
                  real(QPSK_map(1))*SVa2(4) + 1j*imag(QPSK_map(1))*SVa2(1) + ...
                  real(QPSK_map(3))*SVa3(4) + 1j*imag(QPSK_map(3))*SVa3(1) ...
                  real(QPSK_map(2))*SVa1(3) + 1j*imag(QPSK_map(2))*SVa1(1) + ...
                  real(QPSK_map(1))*SVa2(3) + 1j*imag(QPSK_map(1))*SVa2(1) + ...
                  real(QPSK_map(3))*SVa3(3) + 1j*imag(QPSK_map(3))*SVa3(1) ...
                  real(QPSK_map(3))*SVa1(4) + 1j*imag(QPSK_map(3))*SVa1(2) + ...
                  real(QPSK_map(1))*SVa2(4) + 1j*imag(QPSK_map(1))*SVa2(2) + ...
                  real(QPSK_map(3))*SVa3(4) + 1j*imag(QPSK_map(3))*SVa3(2) ...
                  real(QPSK_map(4))*SVa1(3) + 1j*imag(QPSK_map(4))*SVa1(2) + ...
                  real(QPSK_map(1))*SVa2(3) + 1j*imag(QPSK_map(1))*SVa2(2) + ...
                  real(QPSK_map(3))*SVa3(3) + 1j*imag(QPSK_map(3))*SVa3(2) ...
                  real(QPSK_map(1))*SVa1(2) + 1j*imag(QPSK_map(1))*SVa1(1) + ...
                  real(QPSK_map(2))*SVa2(2) + 1j*imag(QPSK_map(2))*SVa2(1) + ...
                  real(QPSK_map(3))*SVa3(2) + 1j*imag(QPSK_map(3))*SVa3(1) ...
                  real(QPSK_map(2))*SVa1(1) + 1j*imag(QPSK_map(2))*SVa1(1) + ...
                  real(QPSK_map(2))*SVa2(1) + 1j*imag(QPSK_map(2))*SVa2(1) + ...
                  real(QPSK_map(3))*SVa3(1) + 1j*imag(QPSK_map(3))*SVa3(1) ...
                  real(QPSK_map(3))*SVa1(2) + 1j*imag(QPSK_map(3))*SVa1(2) + ...
                  real(QPSK_map(2))*SVa2(2) + 1j*imag(QPSK_map(2))*SVa2(2) + ...
                  real(QPSK_map(3))*SVa3(2) + 1j*imag(QPSK_map(3))*SVa3(2) ...
                  real(QPSK_map(4))*SVa1(1) + 1j*imag(QPSK_map(4))*SVa1(2) + ...
                  real(QPSK_map(2))*SVa2(1) + 1j*imag(QPSK_map(2))*SVa2(2) + ...
                  real(QPSK_map(3))*SVa3(1) + 1j*imag(QPSK_map(3))*SVa3(2) ...
                  real(QPSK_map(1))*SVa1(4) + 1j*imag(QPSK_map(1))*SVa1(3) + ...
                  real(QPSK_map(3))*SVa2(4) + 1j*imag(QPSK_map(3))*SVa2(3) + ...
                  real(QPSK_map(3))*SVa3(4) + 1j*imag(QPSK_map(3))*SVa3(3) ...
                  real(QPSK_map(2))*SVa1(3) + 1j*imag(QPSK_map(2))*SVa1(3) + ...
                  real(QPSK_map(3))*SVa2(3) + 1j*imag(QPSK_map(3))*SVa2(3) + ...
                  real(QPSK_map(3))*SVa3(3) + 1j*imag(QPSK_map(3))*SVa3(3) ...
                  real(QPSK_map(3))*SVa1(4) + 1j*imag(QPSK_map(3))*SVa1(4) + ...
                  real(QPSK_map(3))*SVa2(4) + 1j*imag(QPSK_map(3))*SVa2(4) + ...
                  real(QPSK_map(3))*SVa3(4) + 1j*imag(QPSK_map(3))*SVa3(4) ...
                  real(QPSK_map(4))*SVa1(3) + 1j*imag(QPSK_map(4))*SVa1(4) + ...
                  real(QPSK_map(3))*SVa2(3) + 1j*imag(QPSK_map(3))*SVa2(4) + ...
                  real(QPSK_map(3))*SVa3(3) + 1j*imag(QPSK_map(3))*SVa3(4) ...
                  real(QPSK_map(1))*SVa1(2) + 1j*imag(QPSK_map(1))*SVa1(3) + ...
                  real(QPSK_map(4))*SVa2(2) + 1j*imag(QPSK_map(4))*SVa2(3) + ...
                  real(QPSK_map(3))*SVa3(2) + 1j*imag(QPSK_map(3))*SVa3(3) ...
                  real(QPSK_map(2))*SVa1(1) + 1j*imag(QPSK_map(2))*SVa1(3) + ...
                  real(QPSK_map(4))*SVa2(1) + 1j*imag(QPSK_map(4))*SVa2(3) + ...
                  real(QPSK_map(3))*SVa3(1) + 1j*imag(QPSK_map(3))*SVa3(3) ...
                  real(QPSK_map(3))*SVa1(2) + 1j*imag(QPSK_map(3))*SVa1(4) + ...
                  real(QPSK_map(4))*SVa2(2) + 1j*imag(QPSK_map(4))*SVa2(4) + ...
                  real(QPSK_map(3))*SVa3(2) + 1j*imag(QPSK_map(3))*SVa3(4) ...
                  real(QPSK_map(4))*SVa1(1) + 1j*imag(QPSK_map(4))*SVa1(4) + ...
                  real(QPSK_map(4))*SVa2(1) + 1j*imag(QPSK_map(4))*SVa2(4) + ...
                  real(QPSK_map(3))*SVa3(1) + 1j*imag(QPSK_map(3))*SVa3(4) ...%%% 
                  real(QPSK_map(1))*SVa1(1) + 1j*imag(QPSK_map(1))*SVa1(1) + ...
                  real(QPSK_map(1))*SVa2(1) + 1j*imag(QPSK_map(1))*SVa2(1) + ...
                  real(QPSK_map(4))*SVa3(1) + 1j*imag(QPSK_map(4))*SVa3(1) ...
                  real(QPSK_map(2))*SVa1(2) + 1j*imag(QPSK_map(2))*SVa1(1) + ...
                  real(QPSK_map(1))*SVa2(2) + 1j*imag(QPSK_map(1))*SVa2(1) + ...
                  real(QPSK_map(4))*SVa3(2) + 1j*imag(QPSK_map(4))*SVa3(1) ...
                  real(QPSK_map(3))*SVa1(1) + 1j*imag(QPSK_map(3))*SVa1(2) + ...
                  real(QPSK_map(1))*SVa2(1) + 1j*imag(QPSK_map(1))*SVa2(2) + ...
                  real(QPSK_map(4))*SVa3(1) + 1j*imag(QPSK_map(4))*SVa3(2) ...
                  real(QPSK_map(4))*SVa1(2) + 1j*imag(QPSK_map(4))*SVa1(2) + ...
                  real(QPSK_map(1))*SVa2(2) + 1j*imag(QPSK_map(1))*SVa2(2) + ...
                  real(QPSK_map(4))*SVa3(2) + 1j*imag(QPSK_map(4))*SVa3(2) ...
                  real(QPSK_map(1))*SVa1(3) + 1j*imag(QPSK_map(1))*SVa1(1) + ...
                  real(QPSK_map(2))*SVa2(3) + 1j*imag(QPSK_map(2))*SVa2(1) + ...
                  real(QPSK_map(4))*SVa3(3) + 1j*imag(QPSK_map(4))*SVa3(1) ...
                  real(QPSK_map(2))*SVa1(4) + 1j*imag(QPSK_map(2))*SVa1(1) + ...
                  real(QPSK_map(2))*SVa2(4) + 1j*imag(QPSK_map(2))*SVa2(1) + ...
                  real(QPSK_map(4))*SVa3(4) + 1j*imag(QPSK_map(4))*SVa3(1) ...
                  real(QPSK_map(3))*SVa1(3) + 1j*imag(QPSK_map(3))*SVa1(2) + ...
                  real(QPSK_map(2))*SVa2(3) + 1j*imag(QPSK_map(2))*SVa2(2) + ...
                  real(QPSK_map(4))*SVa3(3) + 1j*imag(QPSK_map(4))*SVa3(2) ...
                  real(QPSK_map(4))*SVa1(4) + 1j*imag(QPSK_map(4))*SVa1(2) + ...
                  real(QPSK_map(2))*SVa2(4) + 1j*imag(QPSK_map(2))*SVa2(2) + ...
                  real(QPSK_map(4))*SVa3(4) + 1j*imag(QPSK_map(4))*SVa3(2) ...
                  real(QPSK_map(1))*SVa1(1) + 1j*imag(QPSK_map(1))*SVa1(3) + ...
                  real(QPSK_map(3))*SVa2(1) + 1j*imag(QPSK_map(3))*SVa2(3) + ...
                  real(QPSK_map(4))*SVa3(1) + 1j*imag(QPSK_map(4))*SVa3(3) ...
                  real(QPSK_map(2))*SVa1(2) + 1j*imag(QPSK_map(2))*SVa1(3) + ...
                  real(QPSK_map(3))*SVa2(2) + 1j*imag(QPSK_map(3))*SVa2(3) + ...
                  real(QPSK_map(4))*SVa3(2) + 1j*imag(QPSK_map(4))*SVa3(3) ...
                  real(QPSK_map(3))*SVa1(1) + 1j*imag(QPSK_map(3))*SVa1(4) + ...
                  real(QPSK_map(3))*SVa2(1) + 1j*imag(QPSK_map(3))*SVa2(4) + ...
                  real(QPSK_map(4))*SVa3(1) + 1j*imag(QPSK_map(4))*SVa3(4) ...
                  real(QPSK_map(4))*SVa1(2) + 1j*imag(QPSK_map(4))*SVa1(4) + ...
                  real(QPSK_map(3))*SVa2(2) + 1j*imag(QPSK_map(3))*SVa2(4) + ...
                  real(QPSK_map(4))*SVa3(2) + 1j*imag(QPSK_map(4))*SVa3(4) ...
                  real(QPSK_map(1))*SVa1(3) + 1j*imag(QPSK_map(1))*SVa1(3) + ...
                  real(QPSK_map(4))*SVa2(3) + 1j*imag(QPSK_map(4))*SVa2(3) + ...
                  real(QPSK_map(4))*SVa3(3) + 1j*imag(QPSK_map(4))*SVa3(3) ...
                  real(QPSK_map(2))*SVa1(4) + 1j*imag(QPSK_map(2))*SVa1(3) + ...
                  real(QPSK_map(4))*SVa2(4) + 1j*imag(QPSK_map(4))*SVa2(3) + ...
                  real(QPSK_map(4))*SVa3(4) + 1j*imag(QPSK_map(4))*SVa3(3) ...
                  real(QPSK_map(3))*SVa1(3) + 1j*imag(QPSK_map(3))*SVa1(4) + ...
                  real(QPSK_map(4))*SVa2(3) + 1j*imag(QPSK_map(4))*SVa2(4) + ...
                  real(QPSK_map(4))*SVa3(3) + 1j*imag(QPSK_map(4))*SVa3(4) ...
                  real(QPSK_map(4))*SVa1(4) + 1j*imag(QPSK_map(4))*SVa1(4) + ...
                  real(QPSK_map(4))*SVa2(4) + 1j*imag(QPSK_map(4))*SVa2(4) + ...
                  real(QPSK_map(4))*SVa3(4) + 1j*imag(QPSK_map(4))*SVa3(4)];
PrP_normFact = (MLD_LUT_PANOMA*MLD_LUT_PANOMA')/64;
MLD_LUT_PANOMA = MLD_LUT_PANOMA/sqrt(PrP_normFact);
data1MSB_LUT = [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 ...
                0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 ...
                0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 ...
                0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1];
data1LSB_LUT = [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 ...
                0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 ...
                0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 ...
                0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1];
data2MSB_LUT = [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 ...
                0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 ...
                0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 ...
                0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1];
data2LSB_LUT = [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 ...
                0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 ...
                0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 ...
                0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1];
data3MSB_LUT = [0*ones(1,32),ones(1,32)];
data3LSB_LUT = [0*ones(1,16),ones(1,16),0*ones(1,16),ones(1,16)];
symbol1_LUT = [1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 ...
               1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 ...
               1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 ...
               1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4];
symbol2_LUT = [1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 ...
               1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 ...
               1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 ...
               1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4];
symbol3_LUT = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
               2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 ...
               3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
               4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4];           
parfor i_snr = 1:size(SNR_dB,2)
    tic
    i_block = 0;
    bit_error_su = 0;
    bit_error1_MLD_PANOMA = 0;                
    bit_error2_MLD_PANOMA = 0;
    bit_error3_MLD_PANOMA = 0;
    %User1 (PANOMA)
    ser_1_PANOMA = 0;correct1_1_PANOMA = 0;correct2_1_PANOMA = 0;correct3_1_PANOMA = 0;correct4_1_PANOMA = 0;
    ser12_1_PANOMA = 0;ser13_1_PANOMA = 0;ser14_1_PANOMA = 0;ser21_1_PANOMA = 0;ser23_1_PANOMA = 0;ser24_1_PANOMA = 0;
    ser31_1_PANOMA = 0;ser32_1_PANOMA = 0;ser34_1_PANOMA = 0;ser41_1_PANOMA = 0;ser42_1_PANOMA = 0;ser43_1_PANOMA = 0;
    %User2 (PANOMA)
    ser_2_PANOMA = 0;correct1_2_PANOMA = 0;correct2_2_PANOMA = 0;correct3_2_PANOMA = 0;correct4_2_PANOMA = 0;
    ser12_2_PANOMA = 0;ser13_2_PANOMA = 0;ser14_2_PANOMA = 0;ser21_2_PANOMA = 0;ser23_2_PANOMA = 0;ser24_2_PANOMA = 0;
    ser31_2_PANOMA = 0;ser32_2_PANOMA = 0;ser34_2_PANOMA = 0;ser41_2_PANOMA = 0;ser42_2_PANOMA = 0;ser43_2_PANOMA = 0;
    %User3 (PANOMA)
    ser_3_PANOMA = 0;correct1_3_PANOMA = 0;correct2_3_PANOMA = 0;correct3_3_PANOMA = 0;correct4_3_PANOMA = 0;
    ser12_3_PANOMA = 0;ser13_3_PANOMA = 0;ser14_3_PANOMA = 0;ser21_3_PANOMA = 0;ser23_3_PANOMA = 0;ser24_3_PANOMA = 0;
    ser31_3_PANOMA = 0;ser32_3_PANOMA = 0;ser34_3_PANOMA = 0;ser41_3_PANOMA = 0;ser42_3_PANOMA = 0;ser43_3_PANOMA = 0;
        while(i_block<=Iter)
        %data generation
        data1 = (rand(1, Data_length)>0.5);
        data2 = (rand(1, Data_length)>0.5);
        data3 = (rand(1, Data_length)>0.5);
        data_su = (rand(1, Data_length)>0.5);
        qpsk_code1 = reshape(data1, 2, Frame_length); %MSB is first row
        qpsk_code2 = reshape(data2, 2, Frame_length); %LSB is second row
        qpsk_code3 = reshape(data3, 2, Frame_length);
        qpsk_code_su = reshape(data_su, 2, Frame_length);
        decimal_su = 2*qpsk_code_su(1,:) + qpsk_code_su(2,:) + 1;
        decimal1 = 2*qpsk_code1(1,:) + qpsk_code1(2,:) + 1;
        decimal2 = 2*qpsk_code2(1,:) + qpsk_code2(2,:) + 1;
        decimal3 = 2*qpsk_code3(1,:) + qpsk_code3(2,:) + 1;
        s1 = QPSK_map(decimal1);
        s2 = QPSK_map(decimal2);
        s3 = QPSK_map(decimal3);
        s_su = QPSK_map(decimal_su);
        ReDataComparison = ((real(s1)==real(s3))&(real(s1)==real(s2))&(real(s2)==real(s3)));
        ReDataComparison = ReDataComparison + (((real(s1)~=real(s3))&(real(s1)~=real(s2))&(real(s2)==real(s3)))|((real(s1)==real(s3))&(real(s1)==real(s2))&(real(s2)==real(s3))));
        ReDataComparison = ReDataComparison + (((real(s1)==real(s3))&(real(s1)~=real(s2))&(real(s2)~=real(s3)))|((real(s1)~=real(s3))&(real(s1)~=real(s2))&(real(s2)~=real(s3)))|((real(s1)~=real(s3))&(real(s1)~=real(s2))&(real(s2)==real(s3)))|((real(s1)==real(s3))&(real(s1)==real(s2))&(real(s2)==real(s3))));
        ReDataComparison = ReDataComparison + (((real(s1)~=real(s3))&(real(s1)==real(s2))&(real(s2)~=real(s3)))|((real(s1)~=real(s3))&(real(s1)~=real(s2))&(real(s2)~=real(s3)))|((real(s1)==real(s3))&(real(s1)~=real(s2))&(real(s2)~=real(s3)))|((real(s1)~=real(s3))&(real(s1)~=real(s2))&(real(s2)==real(s3)))|((real(s1)==real(s3))&(real(s1)==real(s2))&(real(s2)==real(s3))));
        ReAdaptivePowerIndex = ReDataComparison; 
        ImDataComparison = ((imag(s1)==imag(s3))&(imag(s1)==imag(s2))&(imag(s2)==imag(s3)));
        ImDataComparison = ImDataComparison + (((imag(s1)~=imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)==imag(s3)))|((imag(s1)==imag(s3))&(imag(s1)==imag(s2))&(imag(s2)==imag(s3))));
        ImDataComparison = ImDataComparison + (((imag(s1)==imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)~=imag(s3)))|((imag(s1)~=imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)~=imag(s3)))|((imag(s1)~=imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)==imag(s3)))|((imag(s1)==imag(s3))&(imag(s1)==imag(s2))&(imag(s2)==imag(s3))));
        ImDataComparison = ImDataComparison + (((imag(s1)~=imag(s3))&(imag(s1)==imag(s2))&(imag(s2)~=imag(s3)))|((imag(s1)~=imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)~=imag(s3)))|((imag(s1)==imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)~=imag(s3)))|((imag(s1)~=imag(s3))&(imag(s1)~=imag(s2))&(imag(s2)==imag(s3)))|((imag(s1)==imag(s3))&(imag(s1)==imag(s2))&(imag(s2)==imag(s3))));
        ImAdaptivePowerIndex = ImDataComparison; %1: 1&2 are equal; PANOMA
                                                 %2: all different; conventional NOMA
                                                 %3: 2&3 are equal; PANOMA
                                                 %4: all equal; PANOMA
        
        ReA1 = Va1(ReAdaptivePowerIndex);
        ReA2 = Va2(ReAdaptivePowerIndex);
        ReA3 = Va3(ReAdaptivePowerIndex);
        ImA1 = Va1(ImAdaptivePowerIndex);
        ImA2 = Va2(ImAdaptivePowerIndex);
        ImA3 = Va3(ImAdaptivePowerIndex);
        
        %superposition coding
        x_su = sqrt(a_su*Ps)*s_su;
        x_PANOMA = sqrt(ReA1*Ps).*real(s1) + 1j*sqrt(ImA1*Ps).*imag(s1) + ...
                   sqrt(ReA2*Ps).*real(s2) + 1j*sqrt(ImA2*Ps).*imag(s2) + ...
                   sqrt(ReA3*Ps).*real(s3) + 1j*sqrt(ImA3*Ps).*imag(s3);
        x_PANOMA = x_PANOMA/sqrt(PrP_normFact);

        %Rayleigh fading channel 
        h_real = randn(1,3);
        h_img = randn(1,3);
        h = 1/sqrt(2).*(h_real + 1j.*h_img);
        h1 = 1/sqrt(PL(1))*h(1,1);
        h2 = 1/sqrt(PL(2))*h(1,2);
        h3 = 1/sqrt(PL(3))*h(1,2);
        h_su = 1*h(1,1);

        %AWGN
        Sf1 = sqrt(1/(4*N*SNR(i_snr)));
        Sf2 = sqrt(1/(4*N*SNR(i_snr)));
        Sf3 = sqrt(1/(4*N*SNR(i_snr)));
        Sf_su = sqrt(a_su/(4*SNR(i_snr)));
        n1 = (randn(1, Frame_length)+1j*randn(1, Frame_length))*Sf1;
        n2 = (randn(1, Frame_length)+1j*randn(1, Frame_length))*Sf2;
        n3 = (randn(1, Frame_length)+1j*randn(1, Frame_length))*Sf3;
        n_su = (randn(1, Frame_length)+1j*randn(1, Frame_length))*Sf_su;
        
        %Received signal 
        y_su = h_su*x_su + n_su;
        y1_PANOMA = h1*x_PANOMA + n1;
        y2_PANOMA = h2*x_PANOMA + n2;
        y3_PANOMA = h3*x_PANOMA + n3;
        MSE_su = abs(y_su/h_su - QPSK_map.');

        MSE1_PANOMA = abs(y1_PANOMA/h1 - MLD_LUT_PANOMA.');
        MSE2_PANOMA = abs(y2_PANOMA/h2 - MLD_LUT_PANOMA.');
        MSE3_PANOMA = abs(y3_PANOMA/h3 - MLD_LUT_PANOMA.');

        [min_metric_su decis_su] = min(MSE_su);              
        [min_metric1_PANOMA decis1_PANOMA] = min(MSE1_PANOMA);
        [min_metric2_PANOMA decis2_PANOMA] = min(MSE2_PANOMA); 
        [min_metric3_PANOMA decis3_PANOMA] = min(MSE3_PANOMA);
        symbol1_detected_PANOMA = symbol1_LUT(decis1_PANOMA);
        symbol2_detected_PANOMA = symbol2_LUT(decis2_PANOMA);
        symbol3_detected_PANOMA = symbol3_LUT(decis3_PANOMA);
        
        
        
        dataMSB_detected_MLD = dataMSB_LUT(decis_su);
        dataLSB_detected_MLD = dataLSB_LUT(decis_su); 
        data1MSB_detected_MLD_PANOMA = data1MSB_LUT(decis1_PANOMA); 
        data1LSB_detected_MLD_PANOMA = data1LSB_LUT(decis1_PANOMA); 
        data2MSB_detected_MLD_PANOMA = data2MSB_LUT(decis2_PANOMA); 
        data2LSB_detected_MLD_PANOMA = data2LSB_LUT(decis2_PANOMA); 
        data3MSB_detected_MLD_PANOMA = data3MSB_LUT(decis3_PANOMA); 
        data3LSB_detected_MLD_PANOMA = data3LSB_LUT(decis3_PANOMA); 
        
        %Input & output comparison (symbol-based) ==> user1 (PANOMA)
        for i_pctLength = 1:Frame_length
            if (symbol1_detected_PANOMA(i_pctLength)==1)
                if(decimal1(i_pctLength)==1)
                correct1_1_PANOMA = correct1_1_PANOMA + 1;
                elseif(decimal1(i_pctLength)==2)
                    ser12_1_PANOMA = ser12_1_PANOMA + 1; %e1
                elseif(decimal1(i_pctLength)==3)
                    ser13_1_PANOMA = ser13_1_PANOMA + 1; %e2
                elseif(decimal1(i_pctLength)==4)
                    ser14_1_PANOMA = ser14_1_PANOMA + 1; %e4
                end
            elseif (symbol1_detected_PANOMA(i_pctLength)==2)
                if(decimal1(i_pctLength)==1)
                    ser21_1_PANOMA = ser21_1_PANOMA + 1; %e1
                elseif(decimal1(i_pctLength)==2)
                    correct2_1_PANOMA = correct2_1_PANOMA + 1;
                elseif(decimal1(i_pctLength)==3)
                    ser23_1_PANOMA = ser23_1_PANOMA + 1; %e3
                elseif(decimal1(i_pctLength)==4)
                    ser24_1_PANOMA = ser24_1_PANOMA + 1; %e2
                end
            elseif (symbol1_detected_PANOMA(i_pctLength)==3)
                if(decimal1(i_pctLength)==1)
                    ser31_1_PANOMA = ser31_1_PANOMA + 1; %e1
                elseif(decimal1(i_pctLength)==2)
                    ser32_1_PANOMA = ser32_1_PANOMA + 1; %e3
                elseif(decimal1(i_pctLength)==3)
                    correct3_1_PANOMA = correct3_1_PANOMA + 1;
                elseif(decimal1(i_pctLength)==4)
                    ser34_1_PANOMA = ser34_1_PANOMA + 1; %e2
                end
            elseif (symbol1_detected_PANOMA(i_pctLength)==4)
                if(decimal1(i_pctLength)==1)
                    ser41_1_PANOMA = ser41_1_PANOMA + 1; %e3
                elseif(decimal1(i_pctLength)==2)
                    ser42_1_PANOMA = ser42_1_PANOMA + 1; %e1
                elseif(decimal1(i_pctLength)==3)
                    ser43_1_PANOMA = ser43_1_PANOMA + 1; %e2
                elseif(decimal1(i_pctLength)==4)
                    correct4_1_PANOMA = correct4_1_PANOMA + 1;
                end
            end
        end
        %Input & output comparison (symbol-based) ==> user2 (PANOMA)
        for i_pctLength = 1:Frame_length
            if (symbol2_detected_PANOMA(i_pctLength)==1)
                if(decimal2(i_pctLength)==1)
                correct1_2_PANOMA = correct1_2_PANOMA + 1;
                elseif(decimal2(i_pctLength)==2)
                    ser12_2_PANOMA = ser12_2_PANOMA + 1; %e1
                elseif(decimal2(i_pctLength)==3)
                    ser13_2_PANOMA = ser13_2_PANOMA + 1; %e2
                elseif(decimal2(i_pctLength)==4)
                    ser14_2_PANOMA = ser14_2_PANOMA + 1; %e4
                end
            elseif (symbol2_detected_PANOMA(i_pctLength)==2)
                if(decimal2(i_pctLength)==1)
                    ser21_2_PANOMA = ser21_2_PANOMA + 1; %e1
                elseif(decimal2(i_pctLength)==2)
                    correct2_2_PANOMA = correct2_2_PANOMA + 1;
                elseif(decimal2(i_pctLength)==3)
                    ser23_2_PANOMA = ser23_2_PANOMA + 1; %e3
                elseif(decimal2(i_pctLength)==4)
                    ser24_2_PANOMA = ser24_2_PANOMA + 1; %e2
                end
            elseif (symbol2_detected_PANOMA(i_pctLength)==3)
                if(decimal2(i_pctLength)==1)
                    ser31_2_PANOMA = ser31_2_PANOMA + 1; %e1
                elseif(decimal2(i_pctLength)==2)
                    ser32_2_PANOMA = ser32_2_PANOMA + 1; %e3
                elseif(decimal2(i_pctLength)==3)
                    correct3_2_PANOMA = correct3_2_PANOMA + 1;
                elseif(decimal2(i_pctLength)==4)
                    ser34_2_PANOMA = ser34_2_PANOMA + 1; %e2
                end
            elseif (symbol2_detected_PANOMA(i_pctLength)==4)
                if(decimal2(i_pctLength)==1)
                    ser41_2_PANOMA = ser41_2_PANOMA + 1; %e3
                elseif(decimal2(i_pctLength)==2)
                    ser42_2_PANOMA = ser42_2_PANOMA + 1; %e1
                elseif(decimal2(i_pctLength)==3)
                    ser43_2_PANOMA = ser43_2_PANOMA + 1; %e2
                elseif(decimal2(i_pctLength)==4)
                    correct4_2_PANOMA = correct4_2_PANOMA + 1;
                end
            end
        end
        %Input & output comparison (symbol-based) ==> user3 (PANOMA)
        for i_pctLength = 1:Frame_length
            if (symbol3_detected_PANOMA(i_pctLength)==1)
                if(decimal3(i_pctLength)==1)
                correct1_3_PANOMA = correct1_3_PANOMA + 1;
                elseif(decimal3(i_pctLength)==2)
                    ser12_3_PANOMA = ser12_3_PANOMA + 1; %e1
                elseif(decimal3(i_pctLength)==3)
                    ser13_3_PANOMA = ser13_3_PANOMA + 1; %e2
                elseif(decimal3(i_pctLength)==4)
                    ser14_3_PANOMA = ser14_3_PANOMA + 1; %e4
                end
            elseif (symbol3_detected_PANOMA(i_pctLength)==2)
                if(decimal3(i_pctLength)==1)
                    ser21_3_PANOMA = ser21_3_PANOMA + 1; %e1
                elseif(decimal3(i_pctLength)==2)
                    correct2_3_PANOMA = correct2_3_PANOMA + 1;
                elseif(decimal3(i_pctLength)==3)
                    ser23_3_PANOMA = ser23_3_PANOMA + 1; %e3
                elseif(decimal3(i_pctLength)==4)
                    ser24_3_PANOMA = ser24_3_PANOMA + 1; %e2
                end
            elseif (symbol3_detected_PANOMA(i_pctLength)==3)
                if(decimal3(i_pctLength)==1)
                    ser31_3_PANOMA = ser31_3_PANOMA + 1; %e1
                elseif(decimal3(i_pctLength)==2)
                    ser32_3_PANOMA = ser32_3_PANOMA + 1; %e3
                elseif(decimal3(i_pctLength)==3)
                    correct3_3_PANOMA = correct3_3_PANOMA + 1;
                elseif(decimal3(i_pctLength)==4)
                    ser34_3_PANOMA = ser34_3_PANOMA + 1; %e2
                end
            elseif (symbol3_detected_PANOMA(i_pctLength)==4)
                if(decimal3(i_pctLength)==1)
                    ser41_3_PANOMA = ser41_3_PANOMA + 1; %e3
                elseif(decimal3(i_pctLength)==2)
                    ser42_3_PANOMA = ser42_3_PANOMA + 1; %e1
                elseif(decimal3(i_pctLength)==3)
                    ser43_3_PANOMA = ser43_3_PANOMA + 1; %e2
                elseif(decimal3(i_pctLength)==4)
                    correct4_3_PANOMA = correct4_3_PANOMA + 1;
                end
            end
        end

        %Error counting
        bit_error_su = bit_error_su+sum(dataMSB_detected_MLD~=qpsk_code_su(1,:)) ...
            +sum(dataLSB_detected_MLD~=qpsk_code_su(2,:));        
        bit_error1_MLD_PANOMA=bit_error1_MLD_PANOMA+sum(data1MSB_detected_MLD_PANOMA~=qpsk_code1(1,:)) ...
            +sum(data1LSB_detected_MLD_PANOMA~=qpsk_code1(2,:));
        bit_error2_MLD_PANOMA=bit_error2_MLD_PANOMA+sum(data2MSB_detected_MLD_PANOMA~=qpsk_code2(1,:)) ...
            +sum(data2LSB_detected_MLD_PANOMA~=qpsk_code2(2,:));
        bit_error3_MLD_PANOMA=bit_error3_MLD_PANOMA+sum(data3MSB_detected_MLD_PANOMA~=qpsk_code3(1,:)) ...
            +sum(data3LSB_detected_MLD_PANOMA~=qpsk_code3(2,:));
        i_block=i_block+1;
    end
    %BER calculation
    BER_su(i_snr) = bit_error_su/Data_length/Iter;
    BER1_MLD_PANOMA(i_snr)=bit_error1_MLD_PANOMA/Data_length/Iter;
    BER2_MLD_PANOMA(i_snr)=bit_error2_MLD_PANOMA/Data_length/Iter;
    BER3_MLD_PANOMA(i_snr)=bit_error3_MLD_PANOMA/Data_length/Iter;
    BER_avg(i_snr) = (BER1_MLD_PANOMA(i_snr) + BER2_MLD_PANOMA(i_snr) + BER3_MLD_PANOMA(i_snr))/3;
    tber = 0.5*(1 - sqrt(SNR./(1 + SNR)));
    SER_1_PANOMA(i_snr) = ser_1_PANOMA/Iter/Frame_length;
    SER12_1_PANOMA(i_snr) = ser12_1_PANOMA/Iter/Frame_length;
    SER13_1_PANOMA(i_snr) = ser13_1_PANOMA/Iter/Frame_length;
    SER14_1_PANOMA(i_snr) = ser14_1_PANOMA/Iter/Frame_length;
    SER21_1_PANOMA(i_snr) = ser21_1_PANOMA/Iter/Frame_length;
    SER23_1_PANOMA(i_snr) = ser23_1_PANOMA/Iter/Frame_length;
    SER24_1_PANOMA(i_snr) = ser24_1_PANOMA/Iter/Frame_length;
    SER31_1_PANOMA(i_snr) = ser31_1_PANOMA/Iter/Frame_length;
    SER32_1_PANOMA(i_snr) = ser32_1_PANOMA/Iter/Frame_length;
    SER34_1_PANOMA(i_snr) = ser34_1_PANOMA/Iter/Frame_length;
    SER41_1_PANOMA(i_snr) = ser41_1_PANOMA/Iter/Frame_length;
    SER42_1_PANOMA(i_snr) = ser42_1_PANOMA/Iter/Frame_length;
    SER43_1_PANOMA(i_snr) = ser43_1_PANOMA/Iter/Frame_length;
    Correct1_1_PANOMA(i_snr) = correct1_1_PANOMA/Iter/Frame_length;
    Correct2_1_PANOMA(i_snr) = correct2_1_PANOMA/Iter/Frame_length;
    Correct3_1_PANOMA(i_snr) = correct3_1_PANOMA/Iter/Frame_length;
    Correct4_1_PANOMA(i_snr) = correct4_1_PANOMA/Iter/Frame_length;
    
    SER_2_PANOMA(i_snr) = ser_2_PANOMA/Iter/Frame_length;
    SER12_2_PANOMA(i_snr) = ser12_2_PANOMA/Iter/Frame_length;
    SER13_2_PANOMA(i_snr) = ser13_2_PANOMA/Iter/Frame_length;
    SER14_2_PANOMA(i_snr) = ser14_2_PANOMA/Iter/Frame_length;
    SER21_2_PANOMA(i_snr) = ser21_2_PANOMA/Iter/Frame_length;
    SER23_2_PANOMA(i_snr) = ser23_2_PANOMA/Iter/Frame_length;
    SER24_2_PANOMA(i_snr) = ser24_2_PANOMA/Iter/Frame_length;
    SER31_2_PANOMA(i_snr) = ser31_2_PANOMA/Iter/Frame_length;
    SER32_2_PANOMA(i_snr) = ser32_2_PANOMA/Iter/Frame_length;
    SER34_2_PANOMA(i_snr) = ser34_2_PANOMA/Iter/Frame_length;
    SER41_2_PANOMA(i_snr) = ser41_2_PANOMA/Iter/Frame_length;
    SER42_2_PANOMA(i_snr) = ser42_2_PANOMA/Iter/Frame_length;
    SER43_2_PANOMA(i_snr) = ser43_2_PANOMA/Iter/Frame_length;
    Correct1_2_PANOMA(i_snr) = correct1_2_PANOMA/Iter/Frame_length;
    Correct2_2_PANOMA(i_snr) = correct2_2_PANOMA/Iter/Frame_length;
    Correct3_2_PANOMA(i_snr) = correct3_2_PANOMA/Iter/Frame_length;
    Correct4_2_PANOMA(i_snr) = correct4_2_PANOMA/Iter/Frame_length;
    
    SER_3_PANOMA(i_snr) = ser_3_PANOMA/Iter/Frame_length;
    SER12_3_PANOMA(i_snr) = ser12_3_PANOMA/Iter/Frame_length;
    SER13_3_PANOMA(i_snr) = ser13_3_PANOMA/Iter/Frame_length;
    SER14_3_PANOMA(i_snr) = ser14_3_PANOMA/Iter/Frame_length;
    SER21_3_PANOMA(i_snr) = ser21_3_PANOMA/Iter/Frame_length;
    SER23_3_PANOMA(i_snr) = ser23_3_PANOMA/Iter/Frame_length;
    SER24_3_PANOMA(i_snr) = ser24_3_PANOMA/Iter/Frame_length;
    SER31_3_PANOMA(i_snr) = ser31_3_PANOMA/Iter/Frame_length;
    SER32_3_PANOMA(i_snr) = ser32_3_PANOMA/Iter/Frame_length;
    SER34_3_PANOMA(i_snr) = ser34_3_PANOMA/Iter/Frame_length;
    SER41_3_PANOMA(i_snr) = ser41_3_PANOMA/Iter/Frame_length;
    SER42_3_PANOMA(i_snr) = ser42_3_PANOMA/Iter/Frame_length;
    SER43_3_PANOMA(i_snr) = ser43_3_PANOMA/Iter/Frame_length;
    Correct1_3_PANOMA(i_snr) = correct1_3_PANOMA/Iter/Frame_length;
    Correct2_3_PANOMA(i_snr) = correct2_3_PANOMA/Iter/Frame_length;
    Correct3_3_PANOMA(i_snr) = correct3_3_PANOMA/Iter/Frame_length;
    Correct4_3_PANOMA(i_snr) = correct4_3_PANOMA/Iter/Frame_length;
    toc
end
fprintf('This program finished at %s\n', datestr(now,'HH:MM:SS'))

e1_1_PANOMA = SER12_1_PANOMA + SER21_1_PANOMA + SER31_1_PANOMA + SER42_1_PANOMA;
e2_1_PANOMA = SER13_1_PANOMA + SER24_1_PANOMA + SER34_1_PANOMA + SER43_1_PANOMA;
e3_1_PANOMA = SER14_1_PANOMA + SER23_1_PANOMA + SER32_1_PANOMA + SER41_1_PANOMA;
correct_1_PANOMA = Correct1_1_PANOMA + Correct2_1_PANOMA + Correct3_1_PANOMA + Correct4_1_PANOMA;
Capacity_1_PANOMA = -e1_1_PANOMA.*log2(e1_1_PANOMA) - e2_1_PANOMA.*log2(e2_1_PANOMA) - e3_1_PANOMA.*log2(e3_1_PANOMA) - (correct_1_PANOMA.*log2(correct_1_PANOMA));
Capacity_1_PANOMA = 2 - Capacity_1_PANOMA;
e1_2_PANOMA = SER12_2_PANOMA + SER21_2_PANOMA + SER31_2_PANOMA + SER42_2_PANOMA;
e2_2_PANOMA = SER13_2_PANOMA + SER24_2_PANOMA + SER34_2_PANOMA + SER43_2_PANOMA;
e3_2_PANOMA = SER14_2_PANOMA + SER23_2_PANOMA + SER32_2_PANOMA + SER41_2_PANOMA;
correct_2_PANOMA = Correct1_2_PANOMA + Correct2_2_PANOMA + Correct3_2_PANOMA + Correct4_2_PANOMA;
Capacity_2_PANOMA = -e1_2_PANOMA.*log2(e1_2_PANOMA) - e2_2_PANOMA.*log2(e2_2_PANOMA) - e3_2_PANOMA.*log2(e3_2_PANOMA) - (correct_2_PANOMA.*log2(correct_2_PANOMA));
Capacity_2_PANOMA = 2 - Capacity_2_PANOMA;
e1_3_PANOMA = SER12_3_PANOMA + SER21_3_PANOMA + SER31_3_PANOMA + SER42_3_PANOMA;
e2_3_PANOMA = SER13_3_PANOMA + SER24_3_PANOMA + SER34_3_PANOMA + SER43_3_PANOMA;
e3_3_PANOMA = SER14_3_PANOMA + SER23_3_PANOMA + SER32_3_PANOMA + SER41_3_PANOMA;
correct_3_PANOMA = Correct1_3_PANOMA + Correct2_3_PANOMA + Correct3_3_PANOMA + Correct4_3_PANOMA;
Capacity_3_PANOMA = -e1_3_PANOMA.*log2(e1_3_PANOMA) - e2_3_PANOMA.*log2(e2_3_PANOMA) - e3_3_PANOMA.*log2(e3_3_PANOMA) - (correct_3_PANOMA.*log2(correct_3_PANOMA));
Capacity_3_PANOMA = 2 - Capacity_3_PANOMA;

C_PANOMA = Capacity_1_PANOMA + Capacity_2_PANOMA + Capacity_3_PANOMA;
